name: Test Build Only (No Deploy, Railway AutoDeploy used)

on:
  push:
    branches:
      - main  # при любом пуше в main запускается build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Опционально: ты можешь добавить сюда тесты или линтеры, если хочешь
